# Generated by Django 3.1.3 on 2022-10-30 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeshboardTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_Catelog', models.ImageField(default='media/profile.jpg', upload_to='media')),
                ('product_Name', models.CharField(max_length=50)),
                ('product_OfferPrice', models.IntegerField()),
                ('product_Price', models.IntegerField()),
                ('product_Company', models.CharField(max_length=50)),
                ('product_Category', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='Deshboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deshboard_Product_Catelog', models.ImageField(default='media/deshboard/product.jpg', upload_to='media/deshboard')),
                ('deshboard_Product_Name', models.CharField(max_length=50)),
                ('deshboard_Product_Description', models.TextField(blank=True, null=True)),
                ('deshboard_product_URL', models.URLField(max_length=500)),
                ('deshboard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.deshboardtags')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.products')),
            ],
        ),
    ]
