# Generated by Django 3.1.3 on 2022-11-13 17:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deliver_country', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('flatno', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeshboardTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_Catelog', models.ImageField(default='media/profile.jpg', upload_to='media')),
                ('product_Name', models.CharField(max_length=50)),
                ('product_OfferPrice', models.IntegerField()),
                ('product_Price', models.IntegerField()),
                ('product_Company', models.CharField(max_length=50)),
                ('product_Category', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_Tax_Percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField()),
                ('enddate', models.DateField()),
                ('promocode', models.CharField(max_length=100)),
                ('no_of_user', models.IntegerField()),
                ('min_purchase', models.IntegerField()),
                ('fixed_amount_off', models.IntegerField()),
                ('promocode_desc', models.CharField(default='', max_length=200)),
                ('promocode_provider', models.CharField(default='', max_length=200)),
                ('display_promo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='productComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productcomment')),
                ('product_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_feature_Name', models.CharField(max_length=200)),
                ('product_feature_Value', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.BooleanField(default=False)),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('deliveryAddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.deliveryaddress')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='Deshboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deshboard_Product_Catelog', models.ImageField(default='media/deshboard/product.jpg', upload_to='media/deshboard')),
                ('deshboard_Product_Name', models.CharField(max_length=50)),
                ('deshboard_Product_Description', models.TextField(blank=True, null=True)),
                ('deshboard_product_URL', models.URLField(max_length=500)),
                ('deshboard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.deshboardtags')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.products')),
            ],
        ),
    ]
