# Generated by Django 3.1.3 on 2022-11-19 20:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingproregistery',
            name='items',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
