# Generated by Django 3.1.3 on 2022-11-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_deliveryaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField()),
                ('enddate', models.DateField()),
                ('promocode', models.CharField(max_length=100)),
                ('no_of_user', models.IntegerField()),
                ('min_purchase', models.IntegerField()),
                ('fixed_amount_off', models.IntegerField()),
            ],
        ),
    ]
