# Generated by Django 3.1.3 on 2022-11-17 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20221117_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellingProRegistery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.TextField(null=True)),
                ('tax', models.TextField(null=True)),
                ('items', models.TextField(null=True)),
                ('shippingCharge', models.ImageField(upload_to='')),
                ('amount', models.FloatField()),
                ('paidAmount', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'paid'), ('return', 'return')], max_length=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
