# Generated by Django 3.1.3 on 2022-10-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deshboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deshboard_Product_Catelog', models.ImageField(default='media/profile.jpg', upload_to='media')),
                ('deshboard_Product_Name', models.CharField(max_length=50)),
                ('deshboard_Product_Description', models.TextField(blank=True, null=True)),
                ('deshboard_product_URL', models.URLField(max_length=500)),
            ],
        ),
    ]
