# Generated by Django 3.1.3 on 2022-11-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='display_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocode',
            name='promocode_desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
