# Generated by Django 3.1.3 on 2022-11-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sellingproregistery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingproregistery',
            name='shippingCharge',
            field=models.IntegerField(),
        ),
    ]
