# Generated by Django 3.1.3 on 2022-10-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_deshboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deshboard',
            name='deshboard_Product_Catelog',
            field=models.ImageField(default='media/deshboard/product.jpg', upload_to='media/deshboard'),
        ),
    ]
