# Generated by Django 3.1.3 on 2022-11-17 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sellingproregistery_ordertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingproregistery',
            name='id',
        ),
        migrations.AddField(
            model_name='sellingproregistery',
            name='sellingProRegisteryID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
