# Generated by Django 3.1.3 on 2022-11-18 11:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20221118_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingproregistery',
            name='items',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=10100, size=100),
        ),
    ]
