# Generated by Django 3.1.3 on 2022-11-04 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_products_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
