# Generated by Django 3.1.3 on 2022-11-05 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20221105_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_Tax_Percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
