# Generated by Django 3.1.3 on 2022-11-18 12:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20221118_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingproregistery',
            name='coupon',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=2525, size=25),
        ),
        migrations.AlterField(
            model_name='sellingproregistery',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
