# Generated by Django 3.1.3 on 2022-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
