# Generated by Django 3.1.3 on 2022-11-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_sellingproregistery_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingproregistery',
            name='items',
            field=models.JSONField(),
        ),
    ]
