# Generated by Django 3.1.3 on 2022-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20221107_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promocode_provider',
            field=models.CharField(default='', max_length=200),
        ),
    ]
