# Generated by Django 3.1.3 on 2022-11-07 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_promocode_promocode_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_feature', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.products')),
            ],
        ),
    ]
