# Generated by Django 3.1.3 on 2022-11-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_features',
            old_name='product_feature',
            new_name='product_feature_Name',
        ),
        migrations.AddField(
            model_name='product_features',
            name='product_feature_Value',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
